version: "3.9"

services:

   mongodb:
      image: mongo
      restart: always
      ports:
         - 27017:27017
      environment:
         MONGO_INITDB_ROOT_USERNAME: test
         MONGO_INITDB_ROOT_PASSWORD: password
      volumes:
         # for persistence storage
         - ./mongodb-data:/data/db
      